export const dummyFeedbacks = [
  {
    id: 1,
    subject: "Performance Error",
    message: "Great app!",
    rating: 5,
    image: null,
    date: "2023-01-01",
    comment: "Thank you! We're glad you're enjoying the performance.",
  },
  {
    id: 2,
    subject: "Glitch",
    message: "Needs improvement.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut repudiandae tempore aut, molestias mollitia porro delectus earum culpa dolor illum ullam autem officiis adipisci optio libero in! Nisi, et libero.",
    rating: 2,
    image:
      "https://imgs.search.brave.com/0t8GGoM4kbGeo1yR1pj73Gz7f8-Zp5rvurwbuZN5O1c/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNDU4/NDY3MjAzL3Bob3Rv/L2dvb2dsZS1vbi1p/cGFkLmpwZz9zPTYx/Mng2MTImdz0wJms9/MjAmYz1SbVF6MDVU/WlA5UFlWajVWdENv/QVZaLXBVNDZlQTA1/QmdZR3dnVkxSUUI0/PQ",
    date: "2023-01-02",
    comment:
      "We’re working on resolving the glitches. Thanks for the heads-up!",
  },
  {
    id: 3,
    subject: "Testing",
    message: "Loved the features!",
    rating: 4,
    image: null,
    date: "2023-01-03",
    comment: "Appreciate the feedback! More features coming soon.",
  },
  {
    id: 4,
    subject: "Performance Error",
    message: "Great app!",
    rating: 5,
    image: null,
    date: "2023-02-04",
    comment: "Awesome to hear! Thanks for the support.",
  },
  {
    id: 5,
    subject: "Glitch",
    message: "Needs improvement.",
    rating: 2,
    image: "/ssdff",
    date: "2023-02-05",
    comment: "We're looking into this issue. Could you provide more details?",
  },
  {
    id: 6,
    subject: "Testing",
    message: "Loved the features!",
    rating: 4,
    image: "/sdfedfd",
    date: "2023-02-06",
    comment: "Glad you like it! Feel free to suggest any features you'd want.",
  },
  {
    id: 7,
    subject: "Performance Error",
    message: "Great app!",
    rating: 5,
    image: null,
    date: "2023-03-07",
    comment: "Thanks! We're committed to keeping it fast and smooth.",
  },
  {
    id: 8,
    subject: "Glitch",
    message: "Needs improvement.",
    rating: 2,
    image: "/ssdff",
    date: "2023-03-08",
    comment: "Sorry for the inconvenience. A fix is on the way!",
  },
  {
    id: 9,
    subject: "Testing",
    message: "Loved the features!",
    rating: 4,
    image: "/sdfedfd",
    date: "2023-03-09",
    comment: "Thanks for testing things out! Stay tuned for updates.",
  },
];
